sudo: false

language: c

compiler:
  - gcc
  - clang

branches:
    only:
        - master
        - develop

env:
    - RUNTIME=libicu
    - RUNTIME=libidn2
    - RUNTIME=libidn
    - RUNTIME=no

addons:
    apt:
        packages:
            - automake
            - autoconf
            - autopoint
            - libtool
            - gtk-doc-tools
            - gettext
            - libidn11
            - libidn11-dev
            - libidn2-0
            - libidn2-0-dev
            - libicu48
            - libicu-dev
            - libunistring0
            - libunistring-dev

script:
  - ./autogen.sh
  - ./configure && make -j4 && make check -j4
  - ./configure --enable-runtime=$RUNTIME --enable-builtin=libicu && make clean && make -j4 && make check -j4
  - ./configure --enable-runtime=$RUNTIME --enable-builtin=libidn2 && make clean && make -j4 && make check -j4
  - ./configure --enable-runtime=$RUNTIME --enable-builtin=libidn && make clean && make -j4 && make check -j4
  - ./configure --enable-runtime=$RUNTIME --disable-builtin && make clean && make -j4 && make check -j4
  - ./configure --enable-gtk-doc && make -j4 && make check -j4
  - make distcheck
